# Used by integration tests
required = ["github.com/bitrise-io/go-utils/envutil",
  "github.com/bitrise-io/envman",
  "github.com/bitrise-io/stepman"]

[[constraint]]
  version = "1.4.2"
  name = "github.com/Sirupsen/logrus"

[[override]]
  name = "github.com/bitrise-io/envman"
  revision = "12078f7c01d109a32410915226323acd6d06f7f8"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/goinp"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/gows"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/stepman"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "e6cf83ec39f6e1158ced1927d4ed14578fda8edb"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2"

[prune]
  go-tests = true
  unused-packages = true
