[[constraint]]
  name = "github.com/Sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/envman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/goinp"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/stepman"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/gows"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"
  